### ISSUE TITLE
issue while login

### ISSUE THREAD

**Issue by Debayanmondal** [SandeepKrSuman/medcare#1]
how to login as admin?

**Comment by SandeepKrSuman** [comment]
**Because the admin dashboard manages critical tasks, there isn't a separate option for logging in as an admin to prevent misuse of admin privileges.**

However, if you're a developer and running your own backend server, it shouldn't pose a significant challenge. It would be simpler if you examine the code closely. You'll need to sign up with the user type set as 'Admin'.
One workaround is to sign up with the user type set as 'Patient' and then manually update the userType field to 'Admin' in your database. That's all there is to it; it's as straightforward as that.

For backend code take a look at [medcare-server](https://github.com/SandeepKrSuman/medcare-server)

Hope this helps. Happy Coding 🚀

**Comment by Debayanmondal** [comment]
Ok thank you for your help sir and your generous reply.
Actually I have started learning Node recently not aware of that thank you
again.

**Comment by SandeepKrSuman** [comment]
You're welcome! Don't hesitate to reach out if you have any further questions or need assistance as you continue learning Node.js. Wishing you all the best on your coding journey! ✨
